export const BASE_URL =
  import.meta.env.VITE_API_URL || "https://samarpanapi.codeeratech.com/admin";
// import.meta.env.VITE_API_URL || "http://localhost:9010/admin";

export const ENDPOINT = {
  LOGIN: "/admin-login",
  ADD_SERVICE: "/add-service",
  GET_ALL_SERVICES: "/get-all-services",
  UPDATE_SERVICE: "/update-services",
  DELETE_SERVICE: "/delete-service",
  ADD_DOCTOR: "/add-doctor",
  GET_ALL_DOCTORS: "/get-all-doctors",
  UPDATE_DOCTOR: "/update-doctor",
  DELETE_DOCTOR: "/delete-doctor",
  GET_ALL_PATIENTS: "/get-all-patients",
  UPDATE_PATIENT: "/update-patient",
  DISCHARGE_PATIENT: "/discharge-patient",
  ADD_REVIEW: "/add-review",
  GET_ALL_REVIEWS: "/get-all-reviews",
  UPDATE_REVIEW: "/update-review",
  DELETE_REVIEW: "/delete-review",
  ADD_SHORT: "/add-short",
  GET_ALL_SHORTS: "/get-all-shorts",
  UPDATE_SHORT: "/update-short",
  DELETE_SHORT: "/delete-short",
  GET_ALL_BLOGS: "/get-all-blogs",
  ADD_BLOG: "/add-blog",
  UPDATE_BLOG: "/update-blog",
  DELETE_BLOG: "/delete-blog",
  GET_ALL_GALLERY: "/get-all-gallery",
  ADD_GALLERY: "/add-gallery",
  DELETE_GALLERY: "/delete-gallery",
  GET_CONTENT: "/get-content",
  UPSERT_CONTENT: "/upsert-content",
  GET_SETTINGS: "/get-settings",
  UPDATE_SETTINGS: "/update-settings",
  UPDATE_ADMIN_ACCOUNT: "/update-admin-account",
  GET_ADMIN_STAFF: "/get-admin-staff",
  ADD_STAFF: "/add-staff",
  UPDATE_STAFF: "/update-staff",
  DELETE_STAFF: "/delete-staff",
  GET_APPOINTMENTS: "/get-appointments",
  UPDATE_APPOINTMENT: "/update-appointment",
  GET_DASHBOARD: "/get-dashboard",
};
